server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: AuthenticationServer
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
        - id: Review-MS
          uri: http://localhost:8090
          predicates:
            - Path=/review-ms/**
          filters:
            - ApiTokenFilter
        - id: User-MS
          uri: http://localhost:8091
          predicates:
            - Path=/user-ms/**
          filters:
            - ApiTokenFilter
        - id: Recommendation-MS
          uri: http://localhost:8092
          predicates:
            - Path=/recommendation-ms/**
          filters:
            - ApiTokenFilter